# Generated by Django 3.2.12 on 2022-05-23 08:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_alter_movie_like_users'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='openDate',
            new_name='releaseDate',
        ),
    ]
